name: MyWordPress
description: |
  # Rancher Demo
version: # Version of the Catalog to be used
category: # Category to be used for searching catalog entries
maintainer: Sunil Enadle
license: # The license
projectURL: # A URL related to the catalog entry
