web:
    image: wordpress
    links:
     - mysql
    environment:
     - WORDPRESS_DB_PASSWORD=password
    volumes:
      - /home/rancher/wordpress:/var/www/html
    ports:
     - 8080:80
    labels:
      io.rancher.scheduler.affinity:host_label: name=wordpress
mysql:
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=wordpress
    labels:
      io.rancher.scheduler.affinity:host_label: name=database